---

PLUGINS:
  - https://raw.githubusercontent.com/kpj/jupyfmt/master/mega-linter-plugin-jupyfmt/jupyfmt.megalinter-descriptor.yml

ENABLE_LINTERS:
  - PYTHON_BLACK
  - BASH_SHELLCHECK
  - SNAKEMAKE_SNAKEFMT
  - MARKDOWN_MARKDOWNLINT
  - JUPYTER_JUPYFMT
  - PERL_PERLCRITIC
  - DOCKERFILE_HADOLINT

VALIDATE_ALL_CODEBASE: true
FORMATTERS_DISABLE_ERRORS: false
FLAVOR_SUGGESTIONS: false
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
DEFAULT_BRANCH: master
# any further fix to LICENSE.md will break licensee's detection scheme
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: LICENSE\.md
# GitHub passes HTML comments verbatime from template so we can't use <!-- markdownlint-disable MD041 -->
FILTER_REGEX_EXCLUDE: (\.github/ISSUE_TEMPLATE/.*\.md)
