author: V-pipe Dev team
timezone: Europe/Zurich
title: V-pipe
email: v-pipe@bsse.ethz.ch
description: > # this means to ignore newlines until "baseurl:"
  Virus NGS Pipeline
  - Bioinformatics pipeline for the analysis of next-generation sequencing data derived from intra-host viral populations.
baseurl: "/V-pipe" # the subpath of your site, e.g. /blog
url: "https://cbg-ethz.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima

# Google Analytics
google_analytics: UA-126950686-1

plugins:
  - jekyll-sitemap
