---
name: Drosphila C virus
# config-file used for the analysis of drosphila C virus Illumina samples
# Lezcano et al., Virus Evolution, 2023, https://doi.org/10.1093/ve/vead074
# NCBI BioProject accession number PRJNA993483

general:
      aligner: "bwa"
      snv_caller: "shorah"

input:
    reference: resources/drosphila_c_virus/NC_001834.1.fasta
    read_length: 100
    paired: true

consensus_bcftools:
    max_coverage: 150000

lofreq:
    consensus: false

snv:
  consensus: false
