---
name: MPXV

general:
    aligner: bwa
    primers_trimmer: samtools
    snv_caller: lofreq
​
input:
    reference: "{VPIPE_BASEDIR}/../resources/mpxv/MT903345.1.fasta"
    primers_file: "{VPIPE_BASEDIR}/../resources/mpxv/primers/MPXV-primer_genome-positions_subset.tsv"
    primers_bedfile: "{VPIPE_BASEDIR}/../resources/mpxv/primers/MPXV-primer_genome-positions_subset.bed"
    datadir: "{VPIPE_BASEDIR}/../resources/samples/"
    samples_file: samples.tsv
​
snv:
    consensus: false
​
preprocessing:
    extra: -ns_max_n 4 -min_qual_mean 20 -trim_qual_left 20 -trim_qual_right 20 -trim_qual_window 10
​
output:
    trim_primers: true
    snv: true
    local: true
    global: false
    visualization: true
    QA: true
