---
name: Poliovirus (MinION)
# config-file used for the analysis of poliovirus MinION samples
# sample accession number: ERR4027774 (Shaw et al., 2020, DOI: https://doi.org/10.1128/jcm.00920-20)

general:
    aligner: minimap
    preprocessor: skip

input:
    reference: resources/polio/AY560657.1.fasta
    paired: false

minimap_align:
    preset: map-ont
