# config-file used for the analysis of poliovirus MinION samples
# sample accession number: ERR4027774 (Shaw et al., 2020, DOI: https://doi.org/10.1128/jcm.00920-20)

general:
    virus_base_config: ""
    aligner: minimap
    preprocessor: skip

input:
    reference: resources/polio/AY560657.1.fasta
    datadir: resources/samples/
    samples_file: config/samples.tsv
    paired: false

output:
    trim_primers: false
    snv: false
    local: false
    global: false
    visualization: false
    QA: false
    diversity: false

minimap_align:
    preset: map-ont
