---
name: Respiratory Syncytial Virus B
# config file for Human respiratory syncytial virus B
# config file is used to process Illumina RSV samples

general:
    preprocessor: "prinseq"
    aligner: "bwa"
    primers_trimmer: "samtools"

input:
    reference: "{VPIPE_BASEDIR}/../resources/rsvb/MT107528.1.fasta"
    primers_bedfile: "{VPIPE_BASEDIR}/../resources/rsvb/RSVB_primers_400_V2.1.bed"
    inserts_bedfile: "{VPIPE_BASEDIR}/../resources/rsvb/RSVB_inserts_400_V2.1.bed"
    read_length: 251

lofreq:
    consensus: false

snv:
    consensus: false
