---
name: SARS-CoV-2
general:
    aligner: "bwa"

input:
    reference: "{VPIPE_BASEDIR}/../resources/sars-cov-2/NC_045512.2.fasta"
    metainfo_file: "{VPIPE_BASEDIR}/../resources/sars-cov-2/metainfo.yaml"
    gff_directory: "{VPIPE_BASEDIR}/../resources/sars-cov-2/gffs/"
    primers_bedfile: "{VPIPE_BASEDIR}/../resources/sars-cov-2/primers/nCoV-2019.primer.bed"
    primers_file: "{VPIPE_BASEDIR}/../resources/sars-cov-2/primers/nCoV-2019.tsv"
    phylogeny_data: "{VPIPE_BASEDIR}/../resources/sars-cov-2/phylogeny/selected_covid_sequences.fasta"

frameshift_deletions_checks:
    genes_gff: "{VPIPE_BASEDIR}/../resources/sars-cov-2/gffs/Genes_NC_045512.2.GFF3"

snv:
    consensus: false

lofreq:
    consensus: false
