name: schemadocs
channels:
  - conda-forge
dependencies:
  - pip
  # others
  - anyconfig
  # json-schema-for-humans dependencies:
  - click >=8.0.1
  - dataclasses >=0.6
  - dataclasses-json # >=0.5.6 # missing! 
  - htmlmin >=0.1.12
  - jinja2 >=3
  - markdown2 # >= 2.4.0 # missing!
  - pygments >=2.10.0
  - pytz >=2021.1
  - pyyaml >=5.4.1
  - requests >=2.26.0
  - pip:
    - json-schema-for-humans

##alternatives:
#npm install json-schema-to-markdown @adobe/jsonschema2md


