method_list: [lofreq_local_haplo,
              shorah_default,
              predicthaplo_local_haplo,
              viloca_alpha_0.00001,
              cliquesnv_local_haplo_tf0.001,
              haplodmf,
              ]
replicate_count: 1
haplotype_generation: null
params_path: config_realdata/params.csv
master_seq_path: null
