method_list: [
              viloca_alpha_0.00001,
              viloca_envp,
              viloca_envp_0.001,
              viloca_uniform,
              viloca_learn_error_params
              ]
replicate_count: 5
haplotype_generation: distance
params_path: config_varyvilocaparams/params.csv
master_seq_path: ../../../../hiv/HXB2.fasta
