name: Publish Website

on:
  push:
  pull_request:

jobs:
  build_n_push:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.9"
          mamba-version: "*"
          channels: conda-forge,bioconda,defaults
          channel-priority: true
          activate-environment: V-pipe
          auto-update-conda: true

      - name: Install dependencies
        run: |
          mamba install --yes snakemake-minimal jupytext sra-tools nbconvert ipykernel
          python -m ipykernel install --user

      - name: Build website
        working-directory: ./docs
        run: ./convert.sh

      - uses: actions/upload-artifact@v2
        with:
          name: JupyterNotebooks
          path: ./docs/*.ipynb
      # - name: Publish
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./docs
