name: Test Docker image 

on:
  push:
    branches:
      - '*'
      - '!master'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Free space
        # HACK fixes 'No space left on device'
        # see: https://github.com/orgs/community/discussions/25678#discussioncomment-5242449
        # NOTE we don't use those, we run everything inside Docker, anyway
        run: rm -rf /opt/hostedtoolcache

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and save
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker,dest=./vpipe-docker.tar.zst,compression=zstd,compression-level=6

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: "( !contains(github.ref, 'master') && !startsWith(github.ref, 'refs/tags') )"
        with:
          name: vpipe-docker
          path: ./vpipe-docker.tar.zst
